In [22]:
import os

In [23]:
# Cell 4: verify the dataset already exists locally
DOWNLOAD_DIR = "../data/player_scores_data"
REQUIRED_FILES = ["competitions.csv", "games.csv", "clubs.csv"]

if not os.path.isdir(DOWNLOAD_DIR):
    raise FileNotFoundError(
        f"Expected local Kaggle dataset at '{DOWNLOAD_DIR}', but the directory does not exist."
    )

missing_files = [
    fname for fname in REQUIRED_FILES if not os.path.exists(os.path.join(DOWNLOAD_DIR, fname))
]

if missing_files:
    raise FileNotFoundError(
        "Local Kaggle dataset is incomplete. Missing files: " + ", ".join(missing_files)
    )

print(f"Using existing Kaggle data in: {DOWNLOAD_DIR}")

Using existing Kaggle data in: ../data/player_scores_data

In [24]:
# Cell 5: see what files are inside
import os

files_in_dir = sorted(os.listdir(DOWNLOAD_DIR))
files_in_dir[:50]

['appearances.csv',
 'club_games.csv',
 'clubs.csv',
 'competitions.csv',
 'countries.csv',
 'game_events.csv',
 'game_lineups.csv',
 'games.csv',
 'national_teams.csv',
 'player_valuations.csv',
 'players.csv',
 'transfers.csv']

In [25]:
import pandas as pd
import os

# Example: load a few likely files if they exist
for fname in ["competitions.csv", "games.csv", "clubs.csv", "players.csv", "transfers.csv", "appearances.csv"]:
    path = os.path.join(DOWNLOAD_DIR, fname)
    if os.path.exists(path):
        df = pd.read_csv(path)
        print(f"\n--- {fname} ---")
        print("shape:", df.shape)
        display(df.head())

--- competitions.csv ---
shape: (67, 11)

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,total_clubs,url
0,A1,bundesliga,bundesliga,first_tier,domestic_league,127,Austria,A1,europa,12.0,https://www.transfermarkt.co.uk/bundesliga/sta...
1,AFAC,afc-asian-cup,afc-asian-cup,afc_asian_cup,national_team_competition,-1,NaN,NaN,asien,NaN,https://www.transfermarkt.co.uk/afc-asian-cup/...
2,AFCN,africa-cup-of-nations,africa-cup-of-nations,africa_cup_of_nations,national_team_competition,-1,NaN,NaN,afrika,NaN,https://www.transfermarkt.co.uk/africa-cup-of-...
3,ARG1,torneo-apertura,torneo-apertura,first_tier,domestic_league,9,Argentina,ARG1,amerika,30.0,https://www.transfermarkt.co.uk/torneo-apertur...
4,AUS1,a-league-men,a-league-men,first_tier,domestic_league,12,Australia,AUS1,asien,12.0,https://www.transfermarkt.co.uk/a-league-men/s...

--- games.csv ---
shape: (86983, 23)

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,...,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,...,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,...,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,...,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition

--- clubs.csv ---
shape: (796, 17)

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,10,arminia-bielefeld,Arminia Bielefeld,L1,NaN,27,25.3,15,55.6,4,SchücoArena,26515,+€5.90m,NaN,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/arminia-bielef...
1,10004,paris-fc,Paris Football Club,FR1,NaN,31,28.5,17,54.8,8,Stade Jean Bouin,19904,€-72.30m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/paris-fc/start...
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.2,6,18.8,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
3,1003,leicester-city,Leicester City,GB1,NaN,29,25.9,17,58.6,9,King Power Stadium,32259,+€57.30m,Steve Cooper,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/leicester-city...
4,1005,us-lecce,Unione Sportiva Lecce,IT1,NaN,27,25.1,23,85.2,10,Ettore Giardiniero,31559,+€8.62m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...

--- players.csv ---
shape: (47702, 26)

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

--- transfers.csv ---
shape: (157186, 10)

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,467994,2030-06-30,25/26,5621,749,Reggiana,FC Empoli,0.0,700000.0,Luca Belardinelli
1,784335,2027-07-18,27/28,6505,6502,Gimcheon Sangmu,Jeonbuk Hyundai,0.0,500000.0,Jun-soo Byeon
2,402135,2027-07-04,27/28,6505,515,Gimcheon Sangmu,Without Club,NaN,350000.0,Jun-su Ahn
3,716435,2027-07-04,27/28,6505,30925,Gimcheon Sangmu,Gwangju FC,0.0,325000.0,Kang-hyun Lee
4,803933,2027-06-30,26/27,4467,14,TSV Hartberg,Austria Vienna,0.0,300000.0,Luca Pazourek

--- appearances.csv ---
shape: (1862208, 13)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,76,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

In [26]:
# Cell 7: save references to dataframes you want
competitions = pd.read_csv(f"{DOWNLOAD_DIR}/competitions.csv")
games = pd.read_csv(f"{DOWNLOAD_DIR}/games.csv")
clubs = pd.read_csv(f"{DOWNLOAD_DIR}/clubs.csv")

print(competitions.shape, games.shape, clubs.shape)
competitions.head()

(67, 11) (86983, 23) (796, 17)

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,total_clubs,url
0,A1,bundesliga,bundesliga,first_tier,domestic_league,127,Austria,A1,europa,12.0,https://www.transfermarkt.co.uk/bundesliga/sta...
1,AFAC,afc-asian-cup,afc-asian-cup,afc_asian_cup,national_team_competition,-1,NaN,NaN,asien,NaN,https://www.transfermarkt.co.uk/afc-asian-cup/...
2,AFCN,africa-cup-of-nations,africa-cup-of-nations,africa_cup_of_nations,national_team_competition,-1,NaN,NaN,afrika,NaN,https://www.transfermarkt.co.uk/africa-cup-of-...
3,ARG1,torneo-apertura,torneo-apertura,first_tier,domestic_league,9,Argentina,ARG1,amerika,30.0,https://www.transfermarkt.co.uk/torneo-apertur...
4,AUS1,a-league-men,a-league-men,first_tier,domestic_league,12,Australia,AUS1,asien,12.0,https://www.transfermarkt.co.uk/a-league-men/s...

# Kaggle Dataset validation

In [27]:
import os
import glob
import pandas as pd
import numpy as np

DATA_DIR = DOWNLOAD_DIR

csv_files = sorted(glob.glob(f"{DATA_DIR}/*.csv"))
tables = {}

for f in csv_files:
    name = os.path.basename(f).replace(".csv", "")
    try:
        tables[name] = pd.read_csv(f, low_memory=False)
        print(f"Loaded {name}: {tables[name].shape}")
    except Exception as e:
        print(f"Failed to load {name}: {e}")

Loaded appearances: (1862208, 13)
Loaded club_games: (173966, 11)
Loaded clubs: (796, 17)
Loaded competitions: (67, 11)
Loaded countries: (118, 8)
Loaded game_events: (1242945, 11)
Loaded game_lineups: (3049833, 10)
Loaded games: (86983, 23)
Loaded national_teams: (118, 17)
Loaded player_valuations: (616377, 6)
Loaded players: (47702, 26)
Loaded transfers: (157186, 10)

## Accuracy Dimension: Great Expectations

Because no external ground truth is available, Accuracy is evaluated here with Great Expectations rules for plausible values such as ages, non-negative measures, and valid match/event ranges.

In [28]:
import importlib
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

accuracy_checks = pv.run_accuracy_checks(tables)
accuracy_summary = pv.summarize_dimension_checks(accuracy_checks)
accuracy_failed_checks = accuracy_checks[accuracy_checks["status"] == "failed"].reset_index(drop=True)

display(accuracy_summary)
display(accuracy_failed_checks)

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
2,accuracy,clubs,4,3,0,47
7,accuracy,players,4,2,0,22
3,accuracy,game_events,1,1,0,17488
4,accuracy,game_lineups,2,1,0,472
0,accuracy,appearances,5,1,0,3
1,accuracy,club_games,4,0,0,0
5,accuracy,games,3,0,0,0
6,accuracy,player_valuations,1,0,0,0
8,accuracy,transfers,2,0,0,0

,dimension,table_name,check_name,description,expectation_type,status,applicable_rows,failed_rows,failed_pct,missing_columns,sample_unexpected_values
0,accuracy,clubs,squad_size_greater_than_zero,Squad size should be greater than 0.,expect_column_values_to_be_between,failed,796,42,5.2764,,"[0, 0, 0, 0, 0]"
1,accuracy,game_events,minute_between_0_and_130,Event minute should be between 0 and 130.,expect_column_values_to_be_between,failed,1242945,17488,1.4070,,"[-1, -1, -1, -1, -1]"
2,accuracy,clubs,average_age_between_15_and_45,Average squad age should be between 15 and 45.,expect_column_values_to_be_between,failed,796,4,0.5025,,"[0.0, 0.0, 0.0, 0.0]"
3,accuracy,clubs,stadium_seats_greater_than_zero,Stadium seats should be greater than 0.,expect_column_values_to_be_between,failed,796,1,0.1256,,[0]
4,accuracy,players,height_in_cm_between_140_and_230,Player height should be between 140 and 230 cm.,expect_column_values_to_be_between,failed,47702,14,0.0293,,"[18.0, 18.0, 19.0, 19.0, 18.0]"
5,accuracy,players,age_at_last_season_between_15_and_50,Derived player age at the recorded last season...,expect_column_values_to_be_between,failed,47702,8,0.0168,,"[14.0, 14.0, 14.0, 14.0, 14.0]"
6,accuracy,game_lineups,shirt_number_between_1_and_99,Numeric shirt numbers should be between 1 and 99.,expect_column_values_to_be_between,failed,3049833,472,0.0155,,"[880.0, 189.0, 203.0, 209.0, 210.0]"
7,accuracy,appearances,minutes_played_between_0_and_130,Minutes played should be between 0 and 130.,expect_column_values_to_be_between,failed,1862208,3,0.0002,,"[135, 135, 148]"

## Consistency Dimension: Great Expectations

Consistency is evaluated with Great Expectations by checking whether dates, season/year fields, and age-format fields use one consistent representation across the dataset.

In [29]:
import importlib
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

consistency_checks = pv.run_consistency_checks(tables)
consistency_summary = pv.summarize_dimension_checks(consistency_checks)
consistency_failed_checks = consistency_checks[consistency_checks["status"] == "failed"].reset_index(drop=True)

display(consistency_summary)
display(consistency_failed_checks)

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,consistency,appearances,1,0,0,0
1,consistency,clubs,2,0,0,0
2,consistency,game_events,1,0,0,0
3,consistency,game_lineups,1,0,0,0
4,consistency,games,2,0,0,0
5,consistency,player_valuations,1,0,0,0
6,consistency,players,3,0,0,0
7,consistency,transfers,2,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

## Completeness Dimension: Great Expectations

Completeness is evaluated by checking missing values, required versus optional fields, non-empty table sizes, and where missingness is concentrated.

In [30]:
import importlib
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

completeness_results = pv.run_completeness_checks(tables)
completeness_table_summary = completeness_results["table_summary"]
completeness_required_issues = completeness_results["required_field_issues"]
completeness_missing_patterns = completeness_results["missing_patterns"]

display(completeness_table_summary)
display(completeness_required_issues)
display(completeness_missing_patterns.head(20))

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

,table_name,rows,columns,missing_cells,missing_cells_pct,rows_with_missing,rows_with_missing_pct,expected_min_rows,size_status
0,players,47702,26,188546,15.2022,47484,99.5430,1,passed
1,game_events,1242945,11,1782275,13.0356,1242945,100.0000,1,passed
2,clubs,796,17,1597,11.8017,796,100.0000,1,passed
3,transfers,157186,10,115681,7.3595,77939,49.5839,1,passed
4,national_teams,118,17,127,6.3310,118,100.0000,1,passed
5,competitions,67,11,42,5.6988,16,23.8806,1,passed
6,club_games,173966,11,104264,5.4485,50786,29.1931,1,passed
7,games,86983,23,82284,4.1129,37108,42.6612,1,passed
8,player_valuations,616377,6,71820,1.9420,71796,11.6481,1,passed
9,appearances,1862208,13,2,0.0000,2,0.0001,1,passed
10,countries,118,8,0,0.0000,0,0.0000,1,passed
11,game_lineups,3049833,10,3,0.0000,3,0.0001,1,passed

,dimension,table_name,check_name,description,expectation_type,status,applicable_rows,failed_rows,failed_pct,missing_columns,sample_unexpected_values
0,completeness,players,date_of_birth_required,date_of_birth is required and should not be mi...,expect_column_values_to_not_be_null,failed,47702,49,0.1027,,"[NaN, NaN, NaN, NaN, NaN]"

,table_name,column_name,field_role,missing_count,missing_pct,pattern
0,clubs,total_market_value,optional,796,100.0000,high_missingness
1,national_teams,coach_name,optional,118,100.0000,high_missingness
2,players,current_national_team_id,optional,44611,93.5202,high_missingness
3,clubs,coach_name,optional,706,88.6935,high_missingness
4,game_events,player_assist_id,optional,1059035,85.2037,high_missingness
5,players,international_caps,optional,29979,62.8464,high_missingness
6,players,international_goals,optional,29979,62.8464,high_missingness
7,game_events,player_in_id,optional,630170,50.6997,high_missingness
8,players,agent_name,optional,22180,46.4970,high_missingness
9,transfers,market_value_in_eur,optional,60848,38.7108,high_missingness
10,transfers,transfer_fee,optional,54833,34.8841,high_missingness
11,players,contract_expiration_date,optional,16488,34.5646,high_missingness
12,club_games,opponent_position,optional,50444,28.9965,high_missingness
13,club_games,own_position,optional,50444,28.9965,high_missingness
14,games,away_club_position,optional,25222,28.9965,high_missingness
15,games,home_club_position,optional,25222,28.9965,high_missingness
16,competitions,total_clubs,optional,16,23.8806,high_missingness
17,competitions,country_name,optional,13,19.4030,some_missingness
18,competitions,domestic_league_code,optional,13,19.4030,some_missingness
19,players,highest_market_value_in_eur,optional,8476,17.7686,some_missingness

## Uniqueness Dimension

Uniqueness is evaluated with exact duplicate rows, strict unique identifiers, subset duplicate keys, and a conservative fuzzy duplicate search for player names.

In [31]:
import importlib
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

uniqueness_results = pv.run_uniqueness_checks(tables)
uniqueness_summary = uniqueness_results["summary"]
uniqueness_strict_issues = uniqueness_results["strict_unique_checks"][uniqueness_results["strict_unique_checks"]["status"] == "failed"].reset_index(drop=True)
uniqueness_subset_issues = uniqueness_results["subset_duplicate_checks"][uniqueness_results["subset_duplicate_checks"]["status"] == "failed"].reset_index(drop=True)
uniqueness_candidate_duplicates = uniqueness_results["candidate_field_reviews"][uniqueness_results["candidate_field_reviews"]["duplicate_count"] > 0].reset_index(drop=True)
uniqueness_fuzzy_candidates = uniqueness_results["fuzzy_duplicate_candidates"]

display(uniqueness_summary)
display(uniqueness_strict_issues)
display(uniqueness_subset_issues)
display(uniqueness_candidate_duplicates)
display(uniqueness_fuzzy_candidates)

                   check_type  issue_count  affected_rows
0            exact_duplicates            0              0
1        strict_unique_fields            0              0
2           subset_duplicates            1             12
3  fuzzy_duplicate_candidates            2              2

Empty DataFrame
Columns: [table_name, column_name, status, duplicate_count, duplicate_pct, note]
Index: []

,table_name,key_fields,status,duplicate_count,duplicate_groups,duplicate_pct
0,game_lineups,"game_id, player_id, club_id",failed,12,12,0.0004

,table_name,column_name,duplicate_count,duplicate_pct,note
0,players,player_code,1335,2.7986,player_code behaves like a slug and may repeat...
1,players,name,1253,2.6267,Player names can repeat across different people.
2,competitions,competition_code,3,4.4776,Competition codes may repeat across countries.
3,competitions,name,3,4.4776,Competition names may repeat across countries.

,table_name,left_player_id,left_name,right_player_id,right_name,date_of_birth,similarity
0,players,508371,Emil Konradsen Ceide,794757,Mikkel Konradsen Ceide,2001-09-03 00:00:00,0.9048
1,players,678376,Luan Freitas,809716,Lucas Freitas,2001-01-20 00:00:00,0.8800

## Outliers Dimension

Outliers are evaluated with the IQR method on meaningful continuous fields such as age, height, market value, attendance, squad size, average age, and stadium seats. IDs, binary fields, and zero-dominant fields such as transfer fees are excluded because IQR would not be informative for them.

In [32]:
import importlib
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

outlier_results = pv.run_outlier_checks(tables)
outlier_summary = outlier_results["summary"]
outlier_examples = outlier_results["examples"]

display(outlier_summary)
display(outlier_examples.head(20))

,table_name,column_name,non_null_count,q1,q3,iqr,lower_bound,upper_bound,outlier_count,outlier_pct
0,player_valuations,market_value_in_eur,616377,200000.0,1500000.00,1300000.00,-1750000.000,3450000.000,87916,14.2633
1,transfers,market_value_in_eur,96338,200000.0,1500000.00,1300000.00,-1750000.000,3450000.000,12226,12.6907
2,players,market_value_in_eur,39226,100000.0,750000.00,650000.00,-875000.000,1725000.000,5566,14.1896
3,players,highest_market_value_in_eur,39226,300000.0,2500000.00,2200000.00,-3000000.000,5800000.000,5333,13.5956
4,games,attendance,76310,4389.0,26310.00,21921.00,-28492.500,59191.500,3178,4.1646
5,players,height_in_cm,43946,177.0,187.00,10.00,162.000,202.000,91,0.2071
6,clubs,squad_size,796,25.0,30.00,5.00,17.500,37.500,73,9.1709
7,clubs,national_team_players,796,1.0,6.00,5.00,-6.500,13.500,38,4.7739
8,clubs,stadium_seats,796,10757.5,32290.25,21532.75,-21541.625,64589.375,27,3.3920
9,players,age_at_last_season,47653,20.0,29.00,9.00,6.500,42.500,18,0.0378
10,clubs,average_age,758,24.8,26.90,2.10,21.650,30.050,12,1.5831

,table_name,column_name,row_id,label,value
0,players,age_at_last_season,15817,Patrick Deman,46.0
1,players,age_at_last_season,22415,Fábio,45.0
2,players,age_at_last_season,26436,Kyriakos Stamatopoulos,45.0
3,players,age_at_last_season,193257,Vladyslav Gelzin,44.0
4,players,age_at_last_season,3476,Brad Friedel,43.0
5,players,height_in_cm,607133,Kevin Gadellaa,210.0
6,players,height_in_cm,52506,Kristof Van Hout,207.0
7,players,height_in_cm,463527,Kjell Scherpen,206.0
8,players,height_in_cm,708678,Isaak Touré,206.0
9,players,height_in_cm,568728,Pape Sy,206.0
10,players,market_value_in_eur,342229,Kylian Mbappé,200000000.0
11,players,market_value_in_eur,418560,Erling Haaland,200000000.0
12,players,market_value_in_eur,937958,Lamine Yamal,200000000.0
13,players,market_value_in_eur,371998,Vinicius Junior,150000000.0
14,players,market_value_in_eur,683840,Pedri,150000000.0
15,players,highest_market_value_in_eur,418560,Erling Haaland,200000000.0
16,players,highest_market_value_in_eur,937958,Lamine Yamal,200000000.0
17,players,highest_market_value_in_eur,371998,Vinicius Junior,200000000.0
18,players,highest_market_value_in_eur,342229,Kylian Mbappé,200000000.0
19,players,highest_market_value_in_eur,28003,Lionel Messi,180000000.0

## Timeliness Dimension

Timeliness is evaluated by validating time-based properties: expected frequency and volume, logical timestamps, seasonal stability, and the absence of unexpected gaps or duplicate time keys.

In [33]:
import importlib
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

timeliness_results = pv.run_timeliness_checks(tables)
timeliness_checks = timeliness_results["checks"]
timeliness_summary = pv.summarize_dimension_checks(timeliness_checks)
timeliness_failed_checks = timeliness_checks[timeliness_checks["status"] == "failed"].reset_index(drop=True)
timeliness_coverage = timeliness_results["coverage"]
timeliness_gap_issues = timeliness_results["monthly_gaps"]
timeliness_season_volume = timeliness_results["season_volume"]
timeliness_seasonal_issues = timeliness_results["seasonal_patterns"][timeliness_results["seasonal_patterns"]["volume_status"] == "failed"].reset_index(drop=True)

display(timeliness_summary)
display(timeliness_failed_checks)
display(timeliness_coverage)
display(timeliness_gap_issues)
display(timeliness_season_volume)
display(timeliness_seasonal_issues.head(20))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
3,timeliness,games,8,5,0,279
2,timeliness,game_lineups,7,4,0,76
1,timeliness,game_events,6,3,0,236
0,timeliness,appearances,7,3,0,20
5,timeliness,transfers,4,2,0,2195
4,timeliness,player_valuations,3,0,0,0

,dimension,table_name,check_name,description,expectation_type,status,applicable_rows,failed_rows,failed_pct,missing_columns,sample_unexpected_values
0,timeliness,game_events,monthly_volume_within_expected_range,Active months should stay within +/-40% of the...,pandas_rule,failed,236,118,50.0000,,"[{""year_month"": ""2006-07"", ""row_count"": 91, ""b..."
1,timeliness,games,monthly_volume_within_expected_range,Active months should stay within +/-40% of the...,pandas_rule,failed,217,92,42.3963,,"[{""year_month"": ""2006-07"", ""row_count"": 6, ""ba..."
2,timeliness,games,no_unexpected_gap_months,Months that are normally active should not be ...,pandas_rule,failed,217,65,29.9539,,"[{""year_month"": ""2006-08"", ""baseline_median"": ..."
3,timeliness,game_events,seasonal_pattern_consistent,Monthly activity should follow the usual seaso...,pandas_rule,failed,168,50,29.7619,,"[{""year_month"": ""2006-07"", ""row_count"": 91, ""b..."
4,timeliness,games,season_volume_within_expected_range,Completed seasons should have game counts with...,pandas_rule,failed,17,5,29.4118,,"[{""season"": 2005, ""game_count"": 64}, {""season""..."
5,timeliness,game_events,no_unexpected_gap_months,Months that are normally active should not be ...,pandas_rule,failed,236,68,28.8136,,"[{""year_month"": ""2006-08"", ""baseline_median"": ..."
6,timeliness,game_lineups,monthly_volume_within_expected_range,Active months should stay within +/-40% of the...,pandas_rule,failed,151,32,21.1921,,"[{""year_month"": ""2014-06"", ""row_count"": 0, ""ba..."
7,timeliness,game_lineups,seasonal_pattern_consistent,Monthly activity should follow the usual seaso...,pandas_rule,failed,149,30,20.1342,,"[{""year_month"": ""2016-06"", ""row_count"": 1852, ..."
8,timeliness,games,seasonal_pattern_consistent,Monthly activity should follow the usual seaso...,pandas_rule,failed,152,27,17.7632,,"[{""year_month"": ""2006-07"", ""row_count"": 6, ""ba..."
9,timeliness,appearances,monthly_volume_within_expected_range,Active months should stay within +/-40% of the...,pandas_rule,failed,150,10,6.6667,,"[{""year_month"": ""2014-03"", ""row_count"": 16926,..."
10,timeliness,appearances,seasonal_pattern_consistent,Monthly activity should follow the usual seaso...,pandas_rule,failed,149,9,6.0403,,"[{""year_month"": ""2014-03"", ""row_count"": 16926,..."
11,timeliness,transfers,no_future_dates,transfer_date should not be later than 2026-04...,pandas_rule,failed,157186,2106,1.3398,,"[""2030-06-30"", ""2027-07-18"", ""2027-07-04"", ""20..."
12,timeliness,game_lineups,no_unexpected_gap_months,Months that are normally active should not be ...,pandas_rule,failed,151,2,1.3245,,"[{""year_month"": ""2014-06"", ""baseline_median"": ..."
13,timeliness,appearances,no_unexpected_gap_months,Months that are normally active should not be ...,pandas_rule,failed,150,1,0.6667,,"[{""year_month"": ""2020-04"", ""baseline_median"": ..."
14,timeliness,games,season_matches_date_year,Game dates should fall in the listed season ye...,pandas_rule,failed,86983,90,0.1035,,"[{""game_id"": 3476206, ""season"": 2019, ""date"": ..."
15,timeliness,transfers,transfer_season_matches_transfer_date,transfer_date should align with the listed tra...,pandas_rule,failed,157186,89,0.0566,,"[{""transfer_date"": ""2030-06-30 00:00:00"", ""tra..."
16,timeliness,game_lineups,no_duplicate_time_keys,"game_id, player_id, club_id, date should uniqu...",pandas_rule,failed,3049833,12,0.0004,,"[{""game_id"": 2345078, ""player_id"": 38957, ""clu..."

,table_name,date_column,rows,valid_dates,invalid_dates,min_date,max_date,unique_days,unique_months,full_months_in_range,unexpected_gap_months,median_monthly_rows,max_monthly_rows
0,appearances,date,1862208,1862208,0,2012-07-03,2026-03-22,4039,160,165,1,13046,22016
1,game_events,date,1242945,1242945,0,2006-06-09,2026-03-25,4356,170,238,68,7104,22837
2,game_lineups,date,3049833,3049833,0,2013-07-02,2026-03-23,3874,151,153,2,20445,49416
3,games,date,86983,86983,0,2006-06-09,2026-03-25,4358,170,238,65,536,1369
4,player_valuations,date,616377,616377,0,2000-01-20,2026-03-30,5657,261,261,0,1207,18985
5,transfers,transfer_date,157186,157186,0,1993-07-01,2030-06-30,5412,331,331,0,93,5637

,table_name,year_month,row_count,baseline_median,pct_diff_from_baseline,gap_status
0,appearances,2020-04,0,13526.0,-100.0,failed
1,game_events,2006-08,0,9104.5,-100.0,failed
2,game_events,2006-09,0,8167.0,-100.0,failed
3,game_events,2006-10,0,7334.5,-100.0,failed
4,game_events,2006-11,0,7017.0,-100.0,failed
...,...,...,...,...,...,...
131,games,2012-02,0,496.5,-100.0,failed
132,games,2012-03,0,413.0,-100.0,failed
133,games,2012-04,0,477.0,-100.0,failed
134,games,2012-05,0,299.0,-100.0,failed
135,games,2020-04,0,477.0,-100.0,failed

    season  game_count  pct_vs_median volume_status
0     2005          64       -98.8772        failed
1     2007          31       -99.4561        failed
2     2009          64       -98.8772        failed
3     2011          31       -99.4561        failed
4     2012        5700         0.0000        passed
5     2013        5826         2.2105        passed
6     2014        5836         2.3860        passed
7     2015        5759         1.0351        passed
8     2016        5699        -0.0175        passed
9     2017        5660        -0.7018        passed
10    2018        5723         0.4035        passed
11    2019        5469        -4.0526        passed
12    2020        5564        -2.3860        passed
13    2021        5939         4.1930        passed
14    2022        6008         5.4035        passed
15    2023        5951         4.4035        passed
16    2024        9998        75.4035        failed
17    2025        7661        34.4035        failed

,table_name,year_month,calendar_month,row_count,baseline_median,pct_diff_from_baseline,volume_status,gap_status
0,appearances,2014-03,3,16926,11901.0,42.2233,failed,passed
1,appearances,2020-03,3,6165,11901.0,-48.1976,failed,passed
2,appearances,2020-04,4,0,13526.0,-100.0000,failed,failed
3,appearances,2020-05,5,1160,9920.0,-88.3065,failed,passed
4,appearances,2020-07,7,10719,2404.0,345.8819,failed,passed
5,appearances,2020-08,8,5407,13391.0,-59.6221,failed,passed
6,appearances,2021-01,1,18881,11651.5,62.0478,failed,passed
7,appearances,2022-10,10,22016,14330.5,53.6304,failed,passed
8,appearances,2022-12,12,4322,14501.0,-70.1952,failed,passed
9,appearances,2025-07,7,4339,2404.0,80.4908,failed,passed
10,game_events,2006-07,7,91,4160.0,-97.8125,failed,passed
11,game_events,2006-08,8,0,9104.5,-100.0000,failed,failed
12,game_events,2006-09,9,0,8167.0,-100.0000,failed,failed
13,game_events,2006-10,10,0,7334.5,-100.0000,failed,failed
14,game_events,2006-11,11,0,7017.0,-100.0000,failed,failed
15,game_events,2006-12,12,0,7331.0,-100.0000,failed,failed
16,game_events,2007-01,1,0,5813.5,-100.0000,failed,failed
17,game_events,2007-02,2,0,6405.0,-100.0000,failed,failed
18,game_events,2007-03,3,0,5362.0,-100.0000,failed,failed
19,game_events,2007-04,4,0,6068.0,-100.0000,failed,failed

## Distribution Dimension

Distribution profiling is applied briefly to relevant numeric and categorical fields to summarize min/max values, distinct counts, central tendency, spread, skewness, kurtosis, and the most frequent categories.

In [34]:
import importlib
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

distribution_results = pv.run_distribution_checks(tables)
distribution_summary = distribution_results["summary"]
distribution_numeric_profiles = distribution_results["numeric_profiles"]
distribution_categorical_profiles = distribution_results["categorical_profiles"]

display(distribution_summary)
display(distribution_numeric_profiles)
display(distribution_categorical_profiles)

,table_name,numeric_fields_profiled,categorical_fields_profiled,high_skew_numeric_fields,high_cardinality_categorical_fields
0,games,5,3,3,2
1,appearances,5,1,5,1
2,clubs,5,1,4,1
3,club_games,4,2,2,0
4,players,3,3,3,0
5,transfers,2,1,2,1
6,game_events,1,1,0,0
7,player_valuations,1,1,1,1
8,competitions,0,3,0,0
9,game_lineups,0,2,0,0

,table_name,column_name,non_null_count,missing_count,missing_pct,distinct_count,min_value,q1,median,mean,q3,max_value,std_dev,skewness,abs_skewness,kurtosis,distribution_type,histogram_payload
0,appearances,red_cards,1862208,0,0.0000,2,0.0,0.0,0.0,3.800000e-03,0.00,1.0,6.150000e-02,16.1496,16.1496,258.8107,exact_frequency,"[{""value"": 0.0, ""count"": 1855149}, {""value"": 1..."
1,appearances,assists,1862208,0,0.0000,7,0.0,0.0,0.0,7.510000e-02,0.00,6.0,2.848000e-01,4.0612,4.0612,18.4873,exact_frequency,"[{""value"": 0.0, ""count"": 1732453}, {""value"": 1..."
2,appearances,goals,1862208,0,0.0000,7,0.0,0.0,0.0,9.540000e-02,0.00,6.0,3.299000e-01,3.8775,3.8775,17.8819,exact_frequency,"[{""value"": 0.0, ""count"": 1703114}, {""value"": 1..."
3,appearances,yellow_cards,1862208,0,0.0000,3,0.0,0.0,0.0,1.458000e-01,0.00,2.0,3.637000e-01,2.2457,2.2457,3.8342,exact_frequency,"[{""value"": 0.0, ""count"": 1597906}, {""value"": 1..."
4,appearances,minutes_played,1862208,0,0.0000,122,1.0,45.0,90.0,6.863820e+01,90.00,148.0,3.015030e+01,-1.0376,1.0376,-0.4511,equal_width_bins,"[{""bin_start"": 0.853, ""bin_end"": 19.375, ""coun..."
5,club_games,opponent_goals,173966,0,0.0000,18,0.0,0.0,1.0,1.463400e+00,2.00,19.0,1.400900e+00,1.4601,1.4601,4.1857,equal_width_bins,"[{""bin_start"": -0.019, ""bin_end"": 2.375, ""coun..."
6,club_games,own_goals,173966,0,0.0000,18,0.0,0.0,1.0,1.463400e+00,2.00,19.0,1.400900e+00,1.4601,1.4601,4.1857,equal_width_bins,"[{""bin_start"": -0.019, ""bin_end"": 2.375, ""coun..."
7,club_games,opponent_position,123522,50444,28.9965,21,1.0,5.0,9.0,9.231300e+00,13.00,21.0,5.282400e+00,0.1797,0.1797,-1.0371,equal_width_bins,"[{""bin_start"": 0.98, ""bin_end"": 3.5, ""count"": ..."
8,club_games,own_position,123522,50444,28.9965,21,1.0,5.0,9.0,9.231300e+00,13.00,21.0,5.282400e+00,0.1797,0.1797,-1.0371,equal_width_bins,"[{""bin_start"": 0.98, ""bin_end"": 3.5, ""count"": ..."
9,clubs,average_age,758,38,4.7739,83,0.0,24.8,25.9,2.568480e+01,26.90,30.9,2.436600e+00,-6.2339,6.2339,63.4037,equal_width_bins,"[{""bin_start"": -0.0309, ""bin_end"": 3.862, ""cou..."
10,clubs,squad_size,796,0,0.0000,38,0.0,25.0,28.0,2.646480e+01,30.00,52.0,7.650200e+00,-2.1693,2.1693,5.8003,equal_width_bins,"[{""bin_start"": -0.052, ""bin_end"": 6.5, ""count""..."
11,clubs,national_team_players,796,0,0.0000,23,0.0,1.0,2.5,3.989900e+00,6.00,22.0,4.420900e+00,1.4338,1.4338,1.6379,equal_width_bins,"[{""bin_start"": -0.022, ""bin_end"": 2.75, ""count..."
12,clubs,stadium_seats,796,0,0.0000,656,0.0,10757.5,20008.0,2.420527e+04,32290.25,85018.0,1.746544e+04,1.1385,1.1385,0.9130,equal_width_bins,"[{""bin_start"": -85.018, ""bin_end"": 10627.25, ""..."
13,clubs,foreigners_percentage,739,57,7.1608,247,2.4,24.1,40.0,4.082560e+01,55.60,100.0,2.057180e+01,0.2030,0.2030,-0.7315,equal_width_bins,"[{""bin_start"": 2.302, ""bin_end"": 14.6, ""count""..."
14,game_events,minute,1242945,0,0.0000,121,-1.0,46.0,67.0,6.204780e+01,80.00,120.0,2.343710e+01,-0.8001,0.8001,0.0217,equal_width_bins,"[{""bin_start"": -1.121, ""bin_end"": 14.125, ""cou..."
15,games,away_club_goals,86983,0,0.0000,18,0.0,0.0,1.0,1.329900e+00,2.00,19.0,1.361800e+00,1.6875,1.6875,5.7712,equal_width_bins,"[{""bin_start"": -0.019, ""bin_end"": 2.375, ""coun..."
16,games,attendance,76310,10673,12.2702,32823,1.0,4389.0,12313.0,1.823575e+04,26310.00,99354.0,1.789503e+04,1.3550,1.3550,1.3722,equal_width_bins,"[{""bin_start"": -98.353, ""bin_end"": 12420.125, ..."
17,games,home_club_goals,86983,0,0.0000,16,0.0,1.0,1.0,1.596800e+00,2.00,15.0,1.426500e+00,1.2728,1.2728,3.0550,equal_width_bins,"[{""bin_start"": -0.015, ""bin_end"": 1.875, ""coun..."
18,games,home_club_position,61761,25222,28.9965,21,1.0,5.0,9.0,9.141100e+00,13.00,21.0,5.271500e+00,0.1974,0.1974,-1.0269,equal_width_bins,"[{""bin_start"": 0.98, ""bin_end"": 3.5, ""count"": ..."
19,games,away_club_position,61761,25222,28.9965,21,1.0,5.0,9.0,9.321500e+00,14.00,21.0,5.291800e+00,0.1619,0.1619,-1.0461,equal_width_bins,"[{""bin_start"": 0.98, ""bin_end"": 3.5, ""count"": ..."
20,player_valuations,market_value_in_eur,616377,0,0.0000,425,10000.0,200000.0,500000.0,2.333869e+06,1500000.00,200000000.0,6.766160e+06,8.5653,8.5653,117.2087,equal_width_bins,"[{""bin_start"": -189990.0, ""bin_end"": 25008750...."
21,players,market_value_in_eur,39226,8476,17.7686,119,10000.0,100000.0,275000.0,1.556696e+06,750000.00,200000000.0,5.934682e+06,11.6010,11.6010,216.5336,equal_width_bins,"[{""bin_start"": -189990.0, ""bin_end"": 25008750...."
22,players,highest_market_value_in_eur,39226,8476,17.7686,206,10000.0,300000.0,800000.0,3.528176e+06,2500000.00,200000000.0,9.411834e+06,7.3258,7.3258,81.9574,equal_width_bins,"[{""bin_start"": -189990.0, ""bin_end"": 25008750...."
23,players,height_in_cm,43946,3756,7.8739,56,17.0,177.0,182.0,1.820015e+02,187.00,210.0,7.460000e+00,-3.4166,3.4166,73.4856,equal_width_bins,"[{""bin_start"": 16.807, ""bin_end"": 41.125, ""cou..."
24,transfers,transfer_fee,102353,54833,34.8841,1449,0.0,0.0,0.0,8.023499e+05,0.00,222000000.0,4.441027e+06,12.8273,12.8273,271.1433,equal_width_bins,"[{""bin_start"": -222000.0, ""bin_end"": 27750000...."
25,transfers,market_value_in_eur,96338,60848,38.7108,191,10000.0,200000.0,500000.0,1.882969e+06,1500000.00,180000000.0,4.913449e+06,8.1499,8.1499,115.9987,equal_width_bins,"[{""bin_start"": -169990.0, ""bin_end"": 22508750...."

,table_name,column_name,non_null_count,missing_count,missing_pct,distinct_count,mode_value,mode_count,mode_pct,top_frequencies
0,appearances,competition_id,1862208,0,0.0000,44,IT1,152535,8.1911,"[{""value"": ""IT1"", ""count"": 152535, ""pct"": 8.19..."
1,club_games,hosting,173966,0,0.0000,2,Home,86983,50.0000,"[{""value"": ""Home"", ""count"": 86983, ""pct"": 50.0..."
2,club_games,is_win,173966,0,0.0000,2,0,105773,60.8010,"[{""value"": ""0"", ""count"": 105773, ""pct"": 60.801..."
3,clubs,domestic_competition_id,796,0,0.0000,32,TR1,43,5.4020,"[{""value"": ""TR1"", ""count"": 43, ""pct"": 5.402}, ..."
4,competitions,sub_type,67,0,0.0000,17,first_tier,32,47.7612,"[{""value"": ""first_tier"", ""count"": 32, ""pct"": 4..."
5,competitions,confederation,67,0,0.0000,5,europa,54,80.5970,"[{""value"": ""europa"", ""count"": 54, ""pct"": 80.59..."
6,competitions,type,67,0,0.0000,5,domestic_league,32,47.7612,"[{""value"": ""domestic_league"", ""count"": 32, ""pc..."
7,game_events,type,1242945,0,0.0000,4,Substitutions,613561,49.3635,"[{""value"": ""Substitutions"", ""count"": 613561, ""..."
8,game_lineups,position,3049830,3,0.0001,18,Centre-Back,528844,17.3401,"[{""value"": ""Centre-Back"", ""count"": 528844, ""pc..."
9,game_lineups,type,3049833,0,0.0000,2,starting_lineup,1713512,56.1838,"[{""value"": ""starting_lineup"", ""count"": 1713512..."
10,games,away_club_formation,77827,9156,10.5262,68,4-2-3-1,24204,31.0997,"[{""value"": ""4-2-3-1"", ""count"": 24204, ""pct"": 3..."
11,games,home_club_formation,77701,9282,10.6711,57,4-2-3-1,24860,31.9944,"[{""value"": ""4-2-3-1"", ""count"": 24860, ""pct"": 3..."
12,games,competition_type,86983,0,0.0000,5,domestic_league,61808,71.0576,"[{""value"": ""domestic_league"", ""count"": 61808, ..."
13,player_valuations,player_club_domestic_competition_id,544581,71796,11.6481,32,IT1,49778,9.1406,"[{""value"": ""IT1"", ""count"": 49778, ""pct"": 9.140..."
14,players,sub_position,47247,455,0.9538,13,Centre-Back,8336,17.6434,"[{""value"": ""Centre-Back"", ""count"": 8336, ""pct""..."
15,players,position,47702,0,0.0000,5,Defender,15205,31.8750,"[{""value"": ""Defender"", ""count"": 15205, ""pct"": ..."
16,players,foot,42446,5256,11.0184,3,right,30106,70.9278,"[{""value"": ""right"", ""count"": 30106, ""pct"": 70...."
17,transfers,transfer_season,157186,0,0.0000,35,23/24,15885,10.1059,"[{""value"": ""23/24"", ""count"": 15885, ""pct"": 10...."

## Relationships Dimension

Relationships profiling examines correlations and dependencies between selected fields using Pearson and Spearman correlation, together with a few direct dependency checks for business rules.

In [35]:
import importlib
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

relationship_results = pv.run_relationship_checks(tables)
relationship_summary = relationship_results["summary"]
relationship_correlations = relationship_results["correlations"]
relationship_strong_correlations = relationship_results["strong_correlations"]
relationship_dependency_checks = relationship_results["dependency_checks"]
relationship_failed_dependencies = relationship_dependency_checks[relationship_dependency_checks["status"] == "failed"].reset_index(drop=True)

display(relationship_summary)
display(relationship_strong_correlations)
display(relationship_failed_dependencies)
display(relationship_correlations)

,table_name,correlation_pairs_profiled,strong_pairs,dependency_checks_run,failed_dependency_checks
0,club_games,3,1,1,0
1,clubs,2,1,1,1
2,players,1,1,1,0
3,transfers,1,1,0,0
4,appearances,3,0,0,0
5,games,3,0,0,0

,table_name,left_column,right_column,description,shared_rows,pearson_corr,spearman_corr,max_abs_corr,stronger_method,stronger_corr,direction,strength
0,clubs,foreigners_number,foreigners_percentage,Foreign player count should strongly align wit...,739,0.9681,0.9720,0.9720,spearman,0.9720,positive,very_high
1,players,market_value_in_eur,highest_market_value_in_eur,Current and peak market value should move toge...,39226,0.7612,0.6975,0.7612,pearson,0.7612,positive,high
2,transfers,transfer_fee,market_value_in_eur,Transfer fee should positively relate to marke...,79247,0.6908,0.3547,0.6908,pearson,0.6908,positive,moderate
3,club_games,own_goals,is_win,Scoring more should strongly relate to winning.,173966,0.6126,0.6645,0.6645,spearman,0.6645,positive,moderate

,dimension,table_name,check_name,description,expectation_type,status,applicable_rows,failed_rows,failed_pct,missing_columns,sample_unexpected_values
0,relationships,clubs,foreigners_percentage_matches_counts,foreigners_percentage should match foreigners_...,pandas_rule,failed,739,5,0.6766,,"[{""club_id"": 1095, ""foreigners_percentage"": 57..."

,table_name,left_column,right_column,description,shared_rows,pearson_corr,spearman_corr,max_abs_corr,stronger_method,stronger_corr,direction,strength
0,clubs,foreigners_number,foreigners_percentage,Foreign player count should strongly align wit...,739,0.9681,0.9720,0.9720,spearman,0.9720,positive,very_high
1,players,market_value_in_eur,highest_market_value_in_eur,Current and peak market value should move toge...,39226,0.7612,0.6975,0.7612,pearson,0.7612,positive,high
2,transfers,transfer_fee,market_value_in_eur,Transfer fee should positively relate to marke...,79247,0.6908,0.3547,0.6908,pearson,0.6908,positive,moderate
3,club_games,own_goals,is_win,Scoring more should strongly relate to winning.,173966,0.6126,0.6645,0.6645,spearman,0.6645,positive,moderate
4,club_games,opponent_goals,is_win,Conceding more should relate negatively to win...,173966,-0.4695,-0.5402,0.5402,spearman,-0.5402,negative,moderate
5,club_games,own_position,is_win,Better-ranked teams should generally win more ...,123522,-0.3676,-0.3720,0.3720,spearman,-0.3720,negative,weak
6,games,home_club_goals,home_club_position,Better-ranked home teams tend to score more.,61761,-0.3339,-0.3358,0.3358,spearman,-0.3358,negative,weak
7,games,away_club_goals,away_club_position,Better-ranked away teams tend to score more.,61761,-0.3076,-0.3034,0.3076,pearson,-0.3076,negative,weak
8,games,attendance,home_club_position,Higher-ranked home teams often attract larger ...,55687,-0.2672,-0.2259,0.2672,pearson,-0.2672,negative,very_weak
9,clubs,squad_size,national_team_players,Larger squads often contain more national-team...,796,0.1819,0.1363,0.1819,pearson,0.1819,positive,very_weak
10,appearances,minutes_played,yellow_cards,Longer playing time may slightly increase book...,1862208,0.1082,0.0985,0.1082,pearson,0.1082,positive,very_weak
11,appearances,minutes_played,goals,Longer playing time may weakly increase goal t...,1862208,0.0803,0.0505,0.0803,pearson,0.0803,positive,very_weak
12,appearances,minutes_played,assists,Longer playing time may weakly increase assist...,1862208,0.0791,0.0565,0.0791,pearson,0.0791,positive,very_weak

# API Validation

In [37]:
import importlib
from IPython.display import Markdown
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

api_fixture_params = {
    "league": 39,
    "season": 2024,
    "status": "FT-AET-PEN",
    "timezone": "Africa/Cairo",
}
api_fixture_cache_path = "../data/api_football_fixtures_sample.json"

api_validation_results = pv.run_api_fixture_validation(
    params=api_fixture_params,
    key_path="../key_api.txt",
    cache_path=api_fixture_cache_path,
)
api_request_metadata = api_validation_results["request_metadata"]
api_fixtures = api_validation_results["fixtures"]
api_report_snippets = api_validation_results["report_snippets"]
api_report_lookup = api_report_snippets.set_index("dimension")["report_text"].to_dict()

display(api_request_metadata)
display(api_fixtures.head())

,endpoint,source,cache_path,status_code,elapsed_seconds,request_url,request_params,echoed_parameters,results,response_count,paging_current,paging_total,daily_requests_remaining,minute_requests_remaining,fixture_rows
0,https://v3.football.api-sports.io/fixtures,live_api,D:\DataSince\project\ScoutRadar\data\api_footb...,200,0.7709,https://v3.football.api-sports.io/fixtures?lea...,"{""league"": 39, ""season"": 2024, ""status"": ""FT-A...","{""league"": ""39"", ""season"": ""2024"", ""status"": ""...",380,380,1,1,99,9,380

,fixture_id,fixture_date,fixture_timestamp,status_short,status_long,status_elapsed,league_id,league_name,league_country,season,home_team_id,home_team_name,home_winner,away_team_id,away_team_name,away_winner,home_goals,away_goals
0,1208021,2024-08-16T22:00:00+03:00,1723834800,FT,Match Finished,90,39,Premier League,England,2024,33,Manchester United,True,36,Fulham,False,1,0
1,1208022,2024-08-17T14:30:00+03:00,1723894200,FT,Match Finished,90,39,Premier League,England,2024,57,Ipswich,False,40,Liverpool,True,0,2
2,1208025,2024-08-17T17:00:00+03:00,1723903200,FT,Match Finished,90,39,Premier League,England,2024,34,Newcastle,True,41,Southampton,False,1,0
3,1208023,2024-08-17T17:00:00+03:00,1723903200,FT,Match Finished,90,39,Premier League,England,2024,42,Arsenal,True,39,Wolves,False,2,0
4,1208024,2024-08-17T17:00:00+03:00,1723903200,FT,Match Finished,90,39,Premier League,England,2024,45,Everton,False,51,Brighton,True,0,3

## API Accuracy Dimension

Accuracy is validated on the API wrapper and the flattened fixture sample by checking the endpoint identity, row counts, positive IDs, non-negative goals, and season alignment.

In [38]:
api_accuracy = api_validation_results["accuracy"]
api_accuracy_failed_checks = api_accuracy["checks"][api_accuracy["checks"]["status"] == "failed"].reset_index(drop=True)

display(api_accuracy["summary"])
display(api_accuracy_failed_checks)

display(Markdown(api_report_lookup["Accuracy"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,accuracy,api_fixtures,5,0,0,0
1,accuracy,api_wrapper,5,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

Accuracy was evaluated by checking the API wrapper, row-count agreement, positive identifiers, non-negative goals, and season alignment. All applied accuracy checks passed for the sampled `380` fixtures, so the `/fixtures` response appears logically valid for downstream use.

## API Consistency Dimension

Consistency is validated by comparing echoed request parameters, parsing fixture dates, aligning timestamps with ISO dates, and checking that home and away team fields follow one schema.

In [39]:
api_consistency = api_validation_results["consistency"]
api_consistency_failed_checks = api_consistency["checks"][api_consistency["checks"]["status"] == "failed"].reset_index(drop=True)

display(api_consistency["summary"])
display(api_consistency_failed_checks)

display(Markdown(api_report_lookup["Consistency"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,consistency,api_fixtures,4,0,0,0
1,consistency,api_wrapper,1,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

Consistency was evaluated by comparing echoed parameters, parsing fixture dates, aligning timestamps, and checking the home/away team schema. All consistency checks passed across the sampled `380` fixtures, indicating that the API uses one stable representation for the core fields.

## API Completeness Dimension

Completeness is validated by checking the required wrapper fields, confirming the response is non-empty, and profiling missingness across required and optional flattened fixture fields.

In [40]:
api_completeness = api_validation_results["completeness"]
api_completeness_missing_fields = api_completeness["field_missingness"][api_completeness["field_missingness"]["missing_count"] > 0].reset_index(drop=True)

display(api_completeness["summary"])
display(api_completeness_missing_fields)

display(Markdown(api_report_lookup["Completeness"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,completeness,api_fixtures,14,0,0,0
1,completeness,api_wrapper,7,0,0,0

     table_name  column_name field_role  missing_count  missing_pct
0  api_fixtures  away_winner   optional             93      24.4737
1  api_fixtures  home_winner   optional             93      24.4737

Completeness was evaluated by checking required wrapper fields, confirming that the response was non-empty, and profiling missingness in the flattened fixture fields. The sampled API response was complete for the core required attributes, while any remaining missingness was concentrated in optional fields.

## API Uniqueness Dimension

Uniqueness is validated with exact duplicate checks, fixture ID uniqueness, and duplicate business-key detection on the flattened fixture sample.

In [41]:
api_uniqueness = api_validation_results["uniqueness"]
api_uniqueness_failed_checks = api_uniqueness["checks"][api_uniqueness["checks"]["status"] == "failed"].reset_index(drop=True)

display(api_uniqueness["summary"])
display(api_uniqueness_failed_checks)
display(api_uniqueness["duplicate_rows"].head(20))

display(Markdown(api_report_lookup["Uniqueness"]))

,table_name,rows,exact_duplicate_rows,duplicate_fixture_ids,duplicate_business_keys
0,api_fixtures,380,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

Empty DataFrame
Columns: [fixture_id, fixture_date, fixture_timestamp, status_short, status_long, status_elapsed, league_id, league_name, league_country, season, home_team_id, home_team_name, home_winner, away_team_id, away_team_name, away_winner, home_goals, away_goals]
Index: []

Uniqueness was evaluated using exact duplicate rows and repeated fixture identifiers in the flattened response. No duplicate rows or repeated fixture IDs were detected, so the API sample preserved record uniqueness.

## API Outliers Dimension

Outliers are evaluated with the IQR rule on goals and any available elapsed-time field to flag unusual but still potentially valid football results.

In [42]:
api_outliers = api_validation_results["outliers"]

display(api_outliers["summary"])
display(api_outliers["examples"].head(20))

display(Markdown(api_report_lookup["Outliers"]))

,table_name,column_name,non_null_count,q1,q3,iqr,lower_bound,upper_bound,outlier_count,outlier_pct
0,api_fixtures,home_goals,380,1.0,2.0,1.0,-0.5,3.5,33,8.6842
1,api_fixtures,away_goals,380,1.0,2.0,1.0,-0.5,3.5,21,5.5263

,table_name,column_name,fixture_id,label,value
0,api_fixtures,away_goals,1208040,Wolves vs Chelsea,6
1,api_fixtures,away_goals,1208237,Ipswich vs Manchester City,6
2,api_fixtures,away_goals,1208191,Tottenham vs Liverpool,6
3,api_fixtures,away_goals,1208151,West Ham vs Arsenal,5
4,api_fixtures,away_goals,1208185,Crystal Palace vs Arsenal,5
5,api_fixtures,away_goals,1208212,West Ham vs Liverpool,5
6,api_fixtures,away_goals,1208220,Southampton vs Brentford,5
7,api_fixtures,away_goals,1208181,Southampton vs Tottenham,5
8,api_fixtures,away_goals,1208162,Southampton vs Chelsea,5
9,api_fixtures,away_goals,1208152,Wolves vs Bournemouth,4
10,api_fixtures,home_goals,1208261,Nottingham Forest vs Brighton,7
11,api_fixtures,home_goals,1208311,Newcastle vs Crystal Palace,5
12,api_fixtures,home_goals,1208083,Brentford vs Wolves,5
13,api_fixtures,home_goals,1208254,Arsenal vs Manchester City,5
14,api_fixtures,home_goals,1208243,Bournemouth vs Nottingham Forest,5
15,api_fixtures,home_goals,1208357,Liverpool vs Tottenham,5
16,api_fixtures,home_goals,1208338,Manchester City vs Crystal Palace,5
17,api_fixtures,home_goals,1208039,Tottenham vs Everton,4
18,api_fixtures,home_goals,1208074,Chelsea vs Brighton,4
19,api_fixtures,home_goals,1208121,Tottenham vs Aston Villa,4

Outliers were evaluated with the IQR method on home goals, away goals, and elapsed time when available. The sampled API response produced 54 outlier value(s); these should be treated as extreme football observations rather than automatic data errors.

## API Timeliness Dimension

Timeliness is validated by parsing all fixture dates, checking the requested season window, confirming completed matches are not future-dated, and summarizing date coverage.

In [43]:
api_timeliness = api_validation_results["timeliness"]
api_timeliness_failed_checks = api_timeliness["checks"][api_timeliness["checks"]["status"] == "failed"].reset_index(drop=True)

display(api_timeliness["summary"])
display(api_timeliness["coverage"])
display(api_timeliness_failed_checks)

display(Markdown(api_report_lookup["Timeliness"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,timeliness,api_fixtures,4,0,0,0

,table_name,rows,valid_dates,invalid_dates,min_date,max_date,unique_days,span_days
0,api_fixtures,380,380,0,2024-08-16 19:00:00+00:00,2025-05-25 15:00:00+00:00,109,281

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

Timeliness was evaluated by parsing fixture timestamps, checking the requested season window, and ensuring that completed matches were not future-dated. All timeliness checks passed, indicating that the sampled API records were logically dated and aligned with the requested season.

## API Distribution Dimension

Distribution profiling summarizes the numeric spread of goals and the categorical concentration of statuses and league labels in the sampled fixture response.

In [44]:
api_distribution = api_validation_results["distribution"]

display(api_distribution["summary"])
display(api_distribution["numeric_profiles"])
display(api_distribution["categorical_profiles"])

display(Markdown(api_report_lookup["Distribution"]))

     table_name  numeric_fields_profiled  categorical_fields_profiled
0  api_fixtures                        3                            4

,table_name,column_name,non_null_count,missing_count,missing_pct,distinct_count,min_value,q1,median,mean,q3,max_value,std_dev,skewness,abs_skewness,kurtosis,distribution_type,histogram_payload
0,api_fixtures,away_goals,380,0,0.0,7,0.0,1.0,1.0,1.4211,2.0,6.0,1.1899,1.0387,1.0387,1.5356,exact_frequency,"[{""value"": 0.0, ""count"": 87}, {""value"": 1.0, ""..."
1,api_fixtures,home_goals,380,0,0.0,7,0.0,1.0,1.0,1.5132,2.0,7.0,1.2779,0.8094,0.8094,0.4776,exact_frequency,"[{""value"": 0.0, ""count"": 91}, {""value"": 1.0, ""..."
2,api_fixtures,status_elapsed,380,0,0.0,1,90.0,90.0,90.0,90.0000,90.0,90.0,0.0000,0.0000,0.0000,0.0000,exact_frequency,"[{""value"": 90.0, ""count"": 380}]"

,table_name,column_name,non_null_count,missing_count,missing_pct,distinct_count,most_frequent_value,most_frequent_count,most_frequent_pct,top_values_payload
0,api_fixtures,league_country,380,0,0.0,1,England,380,100.0,"[{""value"": ""England"", ""count"": 380, ""pct"": 100..."
1,api_fixtures,league_name,380,0,0.0,1,Premier League,380,100.0,"[{""value"": ""Premier League"", ""count"": 380, ""pc..."
2,api_fixtures,status_long,380,0,0.0,1,Match Finished,380,100.0,"[{""value"": ""Match Finished"", ""count"": 380, ""pc..."
3,api_fixtures,status_short,380,0,0.0,1,FT,380,100.0,"[{""value"": ""FT"", ""count"": 380, ""pct"": 100.0}]"

Distribution was profiled on the main numeric and categorical API fields, including goals and match-status labels. The main pattern was that goal counts were concentrated in low-scoring values, while `FT` was the dominant status category in the sampled response.

## API Relationships Dimension

Relationships are validated with direct business rules between goals and winner flags to confirm that match outcomes are coherent with the reported score lines.

In [45]:
api_relationships = api_validation_results["relationships"]
api_relationships_failed_checks = api_relationships["checks"][api_relationships["checks"]["status"] == "failed"].reset_index(drop=True)

display(api_relationships["summary"])
display(api_relationships_failed_checks)

display(Markdown(api_report_lookup["Relationships"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,relationships,api_fixtures,3,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

Relationships were evaluated using direct dependency rules between score differences and winner flags. All applied checks passed, indicating that the API preserved the expected match-outcome logic.

In [46]:
display(api_report_snippets)

       dimension  status                                        report_text
0       Accuracy  passed  Accuracy was evaluated by checking the API wra...
1    Consistency  passed  Consistency was evaluated by comparing echoed ...
2   Completeness  passed  Completeness was evaluated by checking require...
3     Uniqueness  passed  Uniqueness was evaluated using exact duplicate...
4       Outliers  passed  Outliers were evaluated with the IQR method on...
5     Timeliness  passed  Timeliness was evaluated by parsing fixture ti...
6   Distribution  passed  Distribution was profiled on the main numeric ...
7  Relationships  passed  Relationships were evaluated using direct depe...

# Merged Dataset Validation

## Merge Strategy

The Kaggle `games.csv` table and the API-Football `/fixtures` sample are merged at the **match level**. This follows the TA definition of merging by **adding more features about the same entity**, where the shared entity is one football match.

The merge uses the mapped competition, season, match date, and normalized home/away team names, then validates the combined table across the same eight quality dimensions.

In [47]:
import importlib
from IPython.display import Markdown
import sys
sys.path.append('../')
from src import validation as pv

# importlib.reload(pv)  # Reload bypassed due to package restructure

merged_raw_dir = DOWNLOAD_DIR if "DOWNLOAD_DIR" in globals() else "../data/player_scores_data"
merged_api_cache_path = api_fixture_cache_path if "api_fixture_cache_path" in globals() else "../data/api_football_fixtures_sample.json"

merged_validation_results = pv.run_merged_fixture_validation(
    raw_dir=merged_raw_dir,
    api_cache_path=merged_api_cache_path,
)

merged_fixtures = merged_validation_results["merged_fixtures"]
merged_merge_summary = merged_validation_results["merge_summary"]
merged_competition_mapping = merged_validation_results["competition_mapping"]
merged_unmatched_api = merged_validation_results["unmatched_api"]
merged_unmatched_kaggle = merged_validation_results["unmatched_kaggle"]
merged_report_snippets = merged_validation_results["report_snippets"]
merged_report_lookup = merged_report_snippets.set_index("dimension")["report_text"].to_dict()

display(merged_merge_summary)
display(merged_competition_mapping)
display(merged_fixtures.head())
display(merged_unmatched_api.head(20))
display(merged_unmatched_kaggle.head(20))

,league_name,league_country,competition_id,competition_name,season_values,api_rows,kaggle_rows_considered,matched_rows,api_unmatched_rows,kaggle_unmatched_rows,api_match_rate_pct,kaggle_match_rate_pct,added_api_features,merge_key,name_aliases_used
0,Premier League,England,GB1,premier-league,2024,380,380,380,0,0,100.0,100.0,18,season + match_date + canonicalized home team ...,wolves->wolverhampton

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,total_clubs,url,name_norm,code_norm,country_norm
0,GB1,premier-league,premier-league,first_tier,domestic_league,189,England,GB1,europa,20.0,https://www.transfermarkt.co.uk/premier-league...,premier league,premier league,england

,api_fixture_id,api_fixture_date,api_fixture_timestamp,api_status_short,api_status_long,api_status_elapsed,api_league_id,api_league_name,api_league_country,season,...,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type,mapped_competition_name,mapped_competition_country,merge_strategy
0,1208021,2024-08-16T22:00:00+03:00,1723834800,FT,Match Finished,90,39,Premier League,England,2024,...,https://www.transfermarkt.co.uk/manchester-uni...,4-2-3-1,4-2-3-1,Manchester United Football Club,Fulham Football Club,1:0,domestic_league,premier-league,England,feature_enrichment_same_match
1,1208023,2024-08-17T17:00:00+03:00,1723903200,FT,Match Finished,90,39,Premier League,England,2024,...,https://www.transfermarkt.co.uk/arsenal-fc_wol...,4-3-3 Attacking,4-2-3-1,Arsenal Football Club,Wolverhampton Wanderers Football Club,2:0,domestic_league,premier-league,England,feature_enrichment_same_match
2,1208024,2024-08-17T17:00:00+03:00,1723903200,FT,Match Finished,90,39,Premier League,England,2024,...,https://www.transfermarkt.co.uk/everton-fc_bri...,4-2-3-1,4-2-3-1,Everton Football Club,Brighton and Hove Albion Football Club,0:3,domestic_league,premier-league,England,feature_enrichment_same_match
3,1208022,2024-08-17T14:30:00+03:00,1723894200,FT,Match Finished,90,39,Premier League,England,2024,...,https://www.transfermarkt.co.uk/ipswich-town_l...,4-2-3-1,4-3-3 Attacking,Ipswich Town,Liverpool Football Club,0:2,domestic_league,premier-league,England,feature_enrichment_same_match
4,1208025,2024-08-17T17:00:00+03:00,1723903200,FT,Match Finished,90,39,Premier League,England,2024,...,https://www.transfermarkt.co.uk/newcastle-unit...,4-3-3 Attacking,3-5-2 flat,Newcastle United Football Club,Southampton FC,1:0,domestic_league,premier-league,England,feature_enrichment_same_match

Empty DataFrame
Columns: [api_fixture_id, api_fixture_date, api_home_team_name, api_away_team_name, season, match_date]
Index: []

Empty DataFrame
Columns: [game_id, date, home_club_name, away_club_name, competition_id, season, match_date]
Index: []

## Merged Accuracy Dimension

Accuracy is evaluated by comparing the two sources after merging, especially the agreement of match scores, dates, season values, and league mapping.

In [48]:
merged_accuracy = merged_validation_results["accuracy"]
merged_accuracy_failed_checks = merged_accuracy["checks"][merged_accuracy["checks"]["status"] == "failed"].reset_index(drop=True)

display(merged_accuracy["summary"])
display(merged_accuracy_failed_checks)

display(Markdown(merged_report_lookup["Accuracy"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,accuracy,merged_fixtures,6,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

Accuracy was evaluated through cross-source agreement on scores, dates, season values, and league mapping. All applied checks passed across the `380` merged matches, so the Kaggle and API records aligned cleanly on the shared match entity.

## Merged Consistency Dimension

Consistency is evaluated by checking that the merged slice represents one competition/league and that the added API status and team fields remain structurally coherent after integration.

In [49]:
merged_consistency = merged_validation_results["consistency"]
merged_consistency_failed_checks = merged_consistency["checks"][merged_consistency["checks"]["status"] == "failed"].reset_index(drop=True)

display(merged_consistency["summary"])
display(merged_consistency_failed_checks)

display(Markdown(merged_report_lookup["Consistency"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,consistency,merged_fixtures,5,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

Consistency was evaluated by checking stable competition coverage plus paired API status and team-identity fields. All consistency checks passed, which indicates that the merged slice used one coherent schema for the integrated match records.

## Merged Completeness Dimension

Completeness is evaluated by checking the required merged fields and by confirming that rows from both sources were fully matched during the integration step.

In [50]:
merged_completeness = merged_validation_results["completeness"]
merged_completeness_missing_fields = merged_completeness["field_missingness"][merged_completeness["field_missingness"]["missing_count"] > 0].reset_index(drop=True)

display(merged_completeness["summary"])
display(merged_completeness_missing_fields)
display(merged_unmatched_api.head(20))
display(merged_unmatched_kaggle.head(20))

display(Markdown(merged_report_lookup["Completeness"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,completeness,merged_fixtures,24,0,0,0

        table_name      column_name field_role  missing_count  missing_pct
0  merged_fixtures  api_away_winner   optional             93      24.4737
1  merged_fixtures  api_home_winner   optional             93      24.4737

Empty DataFrame
Columns: [api_fixture_id, api_fixture_date, api_home_team_name, api_away_team_name, season, match_date]
Index: []

Empty DataFrame
Columns: [game_id, date, home_club_name, away_club_name, competition_id, season, match_date]
Index: []

Completeness was evaluated on required merged fields and merge coverage across both sources. All `380` API fixtures matched `380` Kaggle Premier League rows, and the required merged fields were fully populated.

## Merged Uniqueness Dimension

Uniqueness is evaluated with exact duplicates, `game_id`, `api_fixture_id`, and the merged natural match key to ensure each match appears only once in the integrated dataset.

In [51]:
merged_uniqueness = merged_validation_results["uniqueness"]
merged_uniqueness_failed_checks = merged_uniqueness["checks"][merged_uniqueness["checks"]["status"] == "failed"].reset_index(drop=True)

display(merged_uniqueness["summary"])
display(merged_uniqueness_failed_checks)
display(merged_uniqueness["duplicate_rows"].head(20))

display(Markdown(merged_report_lookup["Uniqueness"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,uniqueness,merged_fixtures,4,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

Empty DataFrame
Columns: [api_fixture_id, api_fixture_date, api_fixture_timestamp, api_status_short, api_status_long, api_status_elapsed, api_league_id, api_league_name, api_league_country, season, api_home_team_id, api_home_team_name, api_home_winner, api_away_team_id, api_away_team_name, api_away_winner, api_home_goals, api_away_goals, api_season, match_date, home_team_key, away_team_key, game_id, competition_id, round, date, home_club_id, away_club_id, home_club_goals, away_club_goals, home_club_position, away_club_position, home_club_manager_name, away_club_manager_name, stadium, attendance, referee, url, home_club_formation, away_club_formation, home_club_name, away_club_name, aggregate, competition_type, mapped_competition_name, mapped_competition_country, merge_strategy]
Index: []

[0 rows x 47 columns]

Uniqueness was evaluated on exact duplicates, `game_id`, `api_fixture_id`, and the merged natural match key. No duplicate merged rows were detected, so both technical identifiers and the business key remained unique.

## Merged Outliers Dimension

Outliers are evaluated on the integrated numeric fields, mainly home goals, away goals, and attendance, using the IQR rule after the merge.

In [52]:
merged_outliers = merged_validation_results["outliers"]

display(merged_outliers["summary"])
display(merged_outliers["examples"].head(20))

display(Markdown(merged_report_lookup["Outliers"]))

,table_name,column_name,non_null_count,q1,q3,iqr,lower_bound,upper_bound,outlier_count,outlier_pct
0,merged_fixtures,home_club_goals,380,1.00,2.00,1.0,-0.5,3.5,33,8.6842
1,merged_fixtures,away_club_goals,380,1.00,2.00,1.0,-0.5,3.5,21,5.5263
2,merged_fixtures,attendance,380,29856.75,56151.25,26294.5,-9585.0,95593.0,0,0.0000

,table_name,column_name,game_id,api_fixture_id,label,value
0,merged_fixtures,away_club_goals,4361280,1208040,Wolverhampton Wanderers Football Club vs Chels...,6
1,merged_fixtures,away_club_goals,4362732,1208237,Ipswich Town vs Manchester City Football Club,6
2,merged_fixtures,away_club_goals,4361488,1208191,Tottenham Hotspur Football Club vs Liverpool F...,6
3,merged_fixtures,away_club_goals,4361448,1208151,West Ham United Football Club vs Arsenal Footb...,5
4,merged_fixtures,away_club_goals,4361482,1208185,Crystal Palace Football Club vs Arsenal Footba...,5
5,merged_fixtures,away_club_goals,4361517,1208220,Southampton FC vs Brentford Football Club,5
6,merged_fixtures,away_club_goals,4361509,1208212,West Ham United Football Club vs Liverpool Foo...,5
7,merged_fixtures,away_club_goals,4361478,1208181,Southampton FC vs Tottenham Hotspur Football Club,5
8,merged_fixtures,away_club_goals,4361459,1208162,Southampton FC vs Chelsea Football Club,5
9,merged_fixtures,away_club_goals,4361449,1208152,Wolverhampton Wanderers Football Club vs Assoc...,4
10,merged_fixtures,home_club_goals,4362756,1208261,Nottingham Forest Football Club vs Brighton an...,7
11,merged_fixtures,home_club_goals,4362806,1208311,Newcastle United Football Club vs Crystal Pala...,5
12,merged_fixtures,home_club_goals,4361382,1208083,Brentford Football Club vs Wolverhampton Wande...,5
13,merged_fixtures,home_club_goals,4362749,1208254,Arsenal Football Club vs Manchester City Footb...,5
14,merged_fixtures,home_club_goals,4362738,1208243,Association Football Club Bournemouth vs Notti...,5
15,merged_fixtures,home_club_goals,4362852,1208357,Liverpool Football Club vs Tottenham Hotspur F...,5
16,merged_fixtures,home_club_goals,4362833,1208338,Manchester City Football Club vs Crystal Palac...,5
17,merged_fixtures,home_club_goals,4361277,1208037,Manchester City Football Club vs Ipswich Town,4
18,merged_fixtures,home_club_goals,4361371,1208072,Arsenal Football Club vs Leicester City,4
19,merged_fixtures,home_club_goals,4361418,1208121,Tottenham Hotspur Football Club vs Aston Villa...,4

Outliers were evaluated with the IQR method on home goals, away goals, and attendance. The merged table produced `54` outlier value(s), which should be interpreted as plausible extreme football outcomes or attendance peaks rather than automatic errors.

## Merged Timeliness Dimension

Timeliness is evaluated by validating the date fields from both sources, checking date alignment between them, confirming season-window validity, and ensuring completed matches are not future-dated.

In [53]:
merged_timeliness = merged_validation_results["timeliness"]
merged_timeliness_failed_checks = merged_timeliness["checks"][merged_timeliness["checks"]["status"] == "failed"].reset_index(drop=True)

display(merged_timeliness["summary"])
display(merged_timeliness_failed_checks)
display(merged_timeliness["coverage"])

display(Markdown(merged_report_lookup["Timeliness"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,timeliness,merged_fixtures,6,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

,table_name,rows,valid_api_dates,invalid_api_dates,min_date,max_date,unique_days,span_days
0,merged_fixtures,380,380,0,2024-08-16 19:00:00+00:00,2025-05-25 15:00:00+00:00,109,281

Timeliness was evaluated by parsing both source dates, checking cross-source date alignment, validating the 2024/2025 season window, and ensuring completed fixtures were not future-dated. All timeliness checks passed, so the merged records were temporally aligned and suitable for downstream analysis.

## Merged Distribution Dimension

Distribution profiling is applied to the merged goals, attendance, formations, and API status fields to summarize how the integrated dataset behaves after merging.

In [54]:
merged_distribution = merged_validation_results["distribution"]

display(merged_distribution["summary"])
display(merged_distribution["numeric_profiles"])
display(merged_distribution["categorical_profiles"])

display(Markdown(merged_report_lookup["Distribution"]))

        table_name  numeric_fields_profiled  categorical_fields_profiled
0  merged_fixtures                        3                            4

,table_name,column_name,non_null_count,missing_count,missing_pct,distinct_count,min_value,q1,median,mean,q3,max_value,std_dev,skewness,abs_skewness,kurtosis,distribution_type,histogram_payload
0,merged_fixtures,attendance,380,0,0.0,347,10992.0,29856.75,34659.0,40474.6079,56151.25,74879.0,16643.5803,0.2896,0.2896,-0.9056,equal_width_bins,"[{""bin_start"": 10928.113, ""bin_end"": 18977.875..."
1,merged_fixtures,away_club_goals,380,0,0.0,7,0.0,1.00,1.0,1.4211,2.00,6.0,1.1899,1.0387,1.0387,1.5356,exact_frequency,"[{""value"": 0.0, ""count"": 87}, {""value"": 1.0, ""..."
2,merged_fixtures,home_club_goals,380,0,0.0,7,0.0,1.00,1.0,1.5132,2.00,7.0,1.2779,0.8094,0.8094,0.4776,exact_frequency,"[{""value"": 0.0, ""count"": 91}, {""value"": 1.0, ""..."

,table_name,column_name,non_null_count,missing_count,missing_pct,distinct_count,most_frequent_value,most_frequent_count,most_frequent_pct,top_values_payload
0,merged_fixtures,api_status_short,380,0,0.0,1,FT,380,100.0000,"[{""value"": ""FT"", ""count"": 380, ""pct"": 100.0}]"
1,merged_fixtures,away_club_formation,380,0,0.0,16,4-2-3-1,195,51.3158,"[{""value"": ""4-2-3-1"", ""count"": 195, ""pct"": 51...."
2,merged_fixtures,competition_type,380,0,0.0,1,domestic_league,380,100.0000,"[{""value"": ""domestic_league"", ""count"": 380, ""p..."
3,merged_fixtures,home_club_formation,380,0,0.0,15,4-2-3-1,207,54.4737,"[{""value"": ""4-2-3-1"", ""count"": 207, ""pct"": 54...."

Distribution was profiled on goals, attendance, match formations, and API match status. The integrated match data remained low-scoring overall, with median home goals of `1.0`, median away goals of `1.0`, and `FT` as the dominant API status.

## Merged Relationships Dimension

Relationships are evaluated by checking whether the API winner flags remain coherent with the final score differences in the merged match records.

In [55]:
merged_relationships = merged_validation_results["relationships"]
merged_relationships_failed_checks = merged_relationships["checks"][merged_relationships["checks"]["status"] == "failed"].reset_index(drop=True)

display(merged_relationships["summary"])
display(merged_relationships_failed_checks)

display(Markdown(merged_report_lookup["Relationships"]))

,dimension,table_name,checks_run,failed_checks,skipped_checks,total_failed_rows
0,relationships,merged_fixtures,3,0,0,0

Empty DataFrame
Columns: [dimension, table_name, check_name, description, expectation_type, status, applicable_rows, failed_rows, failed_pct, missing_columns, sample_unexpected_values]
Index: []

Relationships were evaluated by checking whether API winner flags matched the merged score differences. All dependency checks passed, indicating that the integrated rows preserved the expected link between goals and match outcomes.

In [56]:
display(merged_report_snippets)

       dimension  status                                        report_text
0       Accuracy  passed  Accuracy was evaluated through cross-source ag...
1    Consistency  passed  Consistency was evaluated by checking stable c...
2   Completeness  passed  Completeness was evaluated on required merged ...
3     Uniqueness  passed  Uniqueness was evaluated on exact duplicates, ...
4       Outliers  passed  Outliers were evaluated with the IQR method on...
5     Timeliness  passed  Timeliness was evaluated by parsing both sourc...
6   Distribution  passed  Distribution was profiled on goals, attendance...
7  Relationships  passed  Relationships were evaluated by checking wheth...